### ISSUE TITLE
Ballerina Extension crashes on startup

### ISSUE THREAD

**Issue by Shadow-Devil** [wso2/ballerina-vscode#576]
**Description:**
Following is displayed in the Ballerina logs:
```
Error executing 'bal home'.
<---- cmd output ---->
Cannot read properties of null (reading 'length')<---- cmd output ---->
Plugin version: 4.7.3
Ballerina version: 2201.9.2 (Swan Lake Update 9)
Failed to activate Ballerina extension. Error when checking ballerina version. spawn EINVAL
```

When I execute `bal home` directly via commandline I get the following result:
`C:\PROGRA~1\BALLER~1\DISTRI~1\BALLER~1.2\bin\..`

Under Output -> Ballerina LS Client the following is logged:
```
Error - 2:58:41 PM] Ballerina LS Client client: couldn't create connection to server.
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:799:9)
    at c:\Users\...\.vscode\extensions\wso2.ballerina-4.7.3\dist\extension.js:2:1232327
    at p.createConnection (c:\Users\...\.vscode\extensions\wso2.ballerina-4.7.3\dist\extension.js:2:1068635)
    at p.start (c:\Users\...\.vscode\extensions\wso2.ballerina-4.7.3\dist\extension.js:2:1059150)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows 11
Ballerina 9.2
Extension version v4.7.3

**Comment by lakpahana** [comment]
Temporary Solution : Downgrade to VSC 1.91 and turn off automatic updates.
https://code.visualstudio.com/updates/v1_91
